name: "ChatGPT Code Review"
description: "Sends PR diff to ChatGPT for code review"
inputs:
  chatgpt-api-key:
    required: true
    description: "ChatGPT API key"
runs:
  using: "node20" # Change this to node12, node16, or node20
  main: "dist/index.js"